//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBotGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(no name)")]
        public string DefaultNodeName {
            get {
                return ((string)(this["DefaultNodeName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultPriorityLevel {
            get {
                return ((int)(this["DefaultPriorityLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultNodeRuns {
            get {
                return ((int)(this["DefaultNodeRuns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultVOffset {
            get {
                return ((int)(this["DefaultVOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultHOffset {
            get {
                return ((int)(this["DefaultHOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultMouseSpeed {
            get {
                return ((int)(this["DefaultMouseSpeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultNodeEntropy {
            get {
                return ((int)(this["DefaultNodeEntropy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultForcedPause {
            get {
                return ((int)(this["DefaultForcedPause"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indeterminate")]
        public global::System.Windows.Forms.CheckState DefaultEnabled {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["DefaultEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gbp")]
        public string ProfileFileExtension {
            get {
                return ((string)(this["ProfileFileExtension"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplicationInternodeEntropy {
            get {
                return ((int)(this["ApplicationInternodeEntropy"]));
            }
            set {
                this["ApplicationInternodeEntropy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indeterminate")]
        public global::System.Windows.Forms.CheckState ApplicationIntranodeForcePauseEnabled {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ApplicationIntranodeForcePauseEnabled"]));
            }
            set {
                this["ApplicationIntranodeForcePauseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indeterminate")]
        public global::System.Windows.Forms.CheckState ApplicationIntranodeEntropyEnabled {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ApplicationIntranodeEntropyEnabled"]));
            }
            set {
                this["ApplicationIntranodeEntropyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplicationExecutionScheme {
            get {
                return ((int)(this["ApplicationExecutionScheme"]));
            }
            set {
                this["ApplicationExecutionScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ApplicationTotalRuns {
            get {
                return ((int)(this["ApplicationTotalRuns"]));
            }
            set {
                this["ApplicationTotalRuns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indeterminate")]
        public global::System.Windows.Forms.CheckState ApplicationRunInfinityTimes {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ApplicationRunInfinityTimes"]));
            }
            set {
                this["ApplicationRunInfinityTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplicationGlobalOffsetX {
            get {
                return ((int)(this["ApplicationGlobalOffsetX"]));
            }
            set {
                this["ApplicationGlobalOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplicationGlobalOffsetY {
            get {
                return ((int)(this["ApplicationGlobalOffsetY"]));
            }
            set {
                this["ApplicationGlobalOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indeterminate")]
        public global::System.Windows.Forms.CheckState ApplicationMinimizeWindowOnRun {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ApplicationMinimizeWindowOnRun"]));
            }
            set {
                this["ApplicationMinimizeWindowOnRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProfileDefaultSaveLocation {
            get {
                return ((string)(this["ProfileDefaultSaveLocation"]));
            }
            set {
                this["ProfileDefaultSaveLocation"] = value;
            }
        }
    }
}
